name: Metrics

on:
  # Schedule updates (every Friday at midnight)
  schedule: [{cron: "0 0 * * FRI"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (with public_repo scope)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Drewniok
          template: classic
          base: header, community, repositories, metadata, activity
          config_timezone: Europe/Berlin

          #repositories: 1000
          commits_authoring: Drewniok

          base_indepth: yes

          repositories_skipped: |
            Drewniok/thesis

          # Restrict to public repositories only
          repositories_affiliations: "owner, collaborator"

          plugin_notable: yes
          #plugin_notable_from: organization
          #plugin_notable_indepth: yes
          #plugin_notable_types: pull_request

          #plugin_achievements: yes
          #plugin_achievements_display: detailed
          #plugin_achievements_limit: 3
